# Generated by Django 5.2 on 2025-05-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='model',
            field=models.CharField(blank=True, max_length=255, verbose_name='Модель'),
        ),
    ]
