# Generated by Django 5.2 on 2025-04-26 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Внешний идентификатор'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
