# Generated by Django 5.2 on 2025-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_category_name_alter_parameter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Запуск задачи',
                'verbose_name_plural': 'Запуск задач',
                'managed': False,
            },
        ),
    ]
