name: 'Coverage Report for views.py'

on:
    pull_request:
        branches:
            - main
            - master

permissions:
  contents: read
  pull-requests: write

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.x'

          - name: Install dependencies
            run: |
                pip install -r requirements.txt

          - name: Run migrations
            env:
              DEBUG: "True"
            run: |
                python manage.py migrate --noinput

          - name: Run tests and generate coverage.xml
            env:
              DEBUG: "True"
            run: |
                pytest --cov=backend.views --cov-report xml:coverage.xml -v

          - name: Upload coverage report
            uses: orgoro/coverage@v3.2
            with:
                coverageFile: coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}